apiVersion: v1
kind: ServiceAccount
metadata:
  name: simpleapp-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simpleapp-operator
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["example.com"]
  resources: ["simpleapps", "simpleapps/status"]
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simpleapp-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: simpleapp-operator
  namespace: default
roleRef:
  kind: Role
  name: simpleapp-operator
  apiGroup: rbac.authorization.k8s.io