replicaCount: 5

#settings for nginx image
#  @params image.name is the name of the image
#  @params image.tag is the tag to be used with the image e.g latest

image:
  name: nginx
  tag: 1.27.0


# service.enabled let us decide whether to create a service or not
services:
   svc1:
     type: ClusterIP
     port: 80
   svc2:
     type: NodePort
     port: 30007

containerPorts:
     http: 80
  

#  @param securityContext.enabled 
#  @param securityContext.runAsUser
#  @param securityContext.fsGroup

securityContext: 
  enabled: true
  runAsUser: 1000
  fsGroup: 2000