AWSTemplateFormatVersion: "2010-09-09"
Description: "An Elastic FileSystem"
Parameters:
  FileSystemName:
    Type: String
    Description: "Name of the Elastic File System"
    Default: "MyFileSystem"
  MyVPC:
    Type: String
    Description: "VPC to launch the Elastic File System in"
    Default: vpc-xxxxxxxx
Resources:
  MyFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      AvailabilityZoneName: ap-south-1a
      BackupPolicy: 
           Status: DISABLED
      Encrypted: True
      FileSystemTags: 
        - Key: Name
          Value: MyFileSystem
      PerformanceMode: generalPurpose
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for EFS"
      VpcId: !Ref MyVPC
  MyMountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
        FileSystemId: !Ref MyFileSystem
        SecurityGroups: 
           - !Ref MySecurityGroup
        SubnetId: <subnetID>
