apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mydb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mydb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"