apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacetrackers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ['namespace']
              properties:
                namespace:
                  type: string
                  minLength: 1
            status:
              type: object
              properties:
                creationTimestamp:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ['True', 'False', 'Unknown']
                      lastTransitionTime:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
  scope: Cluster
  names:
    plural: namespacetrackers
    singular: namespacetracker
    kind: NamespaceTracker
    shortNames:
      - nstrack