apiVersion: v1
kind: ConfigMap
metadata:
   name:  {{ include "accessing-files.fullname" . }}
data:
   {{ range $path, $_ := .Files.Glob "files/*.properties"}}
   {{ $path }}: |-
   {{ $.Files.Get $path | nindent 4 }}
   {{ end}}
