AWSTemplateFormatVersion: "2010-09-09"
Description: "My launch template"
Resources:
  MyLaunchTemplate:
  Type: AWS::EC2::LaunchTemplate
  Properties:
    LaunchTemplateData: 
      LaunchTemplateData
    LaunchTemplateName: String
    TagSpecifications: 
      - LaunchTemplateTagSpecification
    VersionDescription: String
