apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project 
  namespace: argocd
spec:
  description: Dev Project
  sourceRepos:
  - '*'

  destinations:
  - namespace: ns-1
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'