{{- if and .Values.securityContext .Values.securityContext.enabled }}
{{- required "securityContext.runAsUser is required when securityContext is enabled" .Values.securityContext.runAsUser -}}
{{- required "securityContext.fsGroup is required when securityContext is enabled" .Values.securityContext.fsGroup -}}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-{{ .Chart.Name }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}  # @param securityContext.runAsUser
            fsGroup: {{ .Values.securityContext.fsGroup }}
          {{ end }}
          {{ if .Values.services | default list | len}}
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
          {{ end }}